import os
import random
import uuid
from datetime import datetime, timedelta
from dotenv import load_dotenv
from typing import List, Dict, Any

# Ensure we're running from the backend directory
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from mongo import mdb, bookings_col, prescriptions_col, diagnoses_col, users_col, vitals_col

def generate_mock_data():
    if mdb is None:
        print("Error: Could not connect to MongoDB.")
        return

    departments = ["Emergency", "Cardiology", "Orthopedics", "Pediatrics", "Neurology"]
    
    # We'll heavily weight Cardiology, Orthopedics, and Neurology to balance out Emergency
    weights = [0.1, 0.3, 0.25, 0.15, 0.2] 

    now = datetime.utcnow()
    
    print("Clearing old mock data from relevant collections to start fresh...")
    # Be careful not to delete real users/system data, just clear the operational collections
    # Option: Just insert NEW data on top of existing data to create a full dashboard.
    # Let's just insert new data to simulate a busy period.
    
    # Generate ~200 random bookings spanning the last 7 days
    num_cases = 200
    
    new_bookings = []
    new_prescriptions = []
    new_diagnoses = []
    new_vitals = []
    
    # Fetch some doctors to assign
    doctors = list(users_col.find({"role": "doctor"}))
    if not doctors:
        print("Warning: No doctors found in DB. Data will have generic doctor names.")
        doctors = [{"name": f"Dr. {dept} Specialist", "department": dept, "_id": str(uuid.uuid4())} for dept in departments]
    
    status_weights = ["completed", "completed", "completed", "completed", "completed", "cancelled", "pending", "pending", "no-show"]

    def random_date_past_days(days=7):
        return now - timedelta(days=random.random() * days, hours=random.random() * 24)

    for i in range(num_cases):
        dept = random.choices(departments, weights)[0]
        
        # Find a doctor for this dept
        dept_doctors = [d for d in doctors if d.get("department") == dept]
        if not dept_doctors:
             dept_doctors = doctors # fallback
             
        doctor = random.choice(dept_doctors)
        status = random.choice(status_weights)
        
        created_at = random_date_past_days()
        
        appointment_date = created_at + timedelta(hours=random.randint(1, 48))
        if appointment_date > now and status == "completed":
            appointment_date = created_at + timedelta(hours=1) # force it in the past
            
        # 1. Booking
        booking_id = str(uuid.uuid4())
        patient_name = f"Patient {random.randint(1000, 9999)}"
        new_bookings.append({
            "booking_id": booking_id,
            "patient_name": patient_name,
            "department": dept,
            "doctor_name": doctor["name"],
            "doctor_id": str(doctor["_id"]),
            "status": status,
            "appointment_date": appointment_date.isoformat(),
            "created_at": created_at.isoformat(),
            "notes": "Generated by simulation script"
        })
        
        # If completed, generate clinical data
        if status == "completed":
            # 2. Prescription
            if random.random() > 0.3: # 70% chance of prescription
                new_prescriptions.append({
                    "prescription_id": f"RX-{random.randint(10000, 99999)}",
                    "patient_name": patient_name,
                    "doctor_name": doctor["name"],
                    "doctor_department": dept,
                    "medication": random.choice(["Amoxicillin", "Lisinopril", "Metformin", "Atorvastatin", "Albuterol", "Omeprazole", "Gabapentin"]),
                    "dosage": "1 tablet daily",
                    "status": "active" if random.random() > 0.5 else "fulfilled",
                    "created_at": (appointment_date + timedelta(minutes=random.randint(10, 30))).isoformat()
                })
                
            # 3. Diagnosis
            if random.random() > 0.2: # 80% chance of diagnosis
                new_diagnoses.append({
                    "diagnosis_id": f"DX-{random.randint(10000, 99999)}",
                    "patient_name": patient_name,
                    "doctor_name": doctor["name"],
                    "doctor_department": dept,
                    "condition": random.choice(["Hypertension", "Type 2 Diabetes", "Asthma", "Osteoarthritis", "Migraine", "Arrhythmia", "Bronchitis"]),
                    "severity": random.choice(["Low", "Medium", "High", "Critical"]),
                    "created_at": (appointment_date + timedelta(minutes=random.randint(5, 15))).isoformat()
                })
                
            # 4. Vitals
            new_vitals.append({
                "patient_name": patient_name,
                "heart_rate": random.randint(60, 100) + (20 if random.random() > 0.8 else 0),
                "blood_pressure": f"{random.randint(110, 150)}/{random.randint(70, 95)}",
                "temperature": round(random.uniform(36.5, 39.0), 1),
                "oxygen_saturation": random.randint(92, 100),
                "recorded_at": appointment_date.isoformat()
            })

    print(f"Inserting {len(new_bookings)} bookings...")
    if new_bookings: bookings_col.insert_many(new_bookings)
    
    print(f"Inserting {len(new_prescriptions)} prescriptions...")
    if new_prescriptions: prescriptions_col.insert_many(new_prescriptions)
    
    print(f"Inserting {len(new_diagnoses)} diagnoses...")
    if new_diagnoses: diagnoses_col.insert_many(new_diagnoses)
    
    print(f"Inserting {len(new_vitals)} patient vitals...")
    if new_vitals: vitals_col.insert_many(new_vitals)

    print("✅ Successfully seeded realistic operational data across all departments.")

if __name__ == "__main__":
    generate_mock_data()
